directories:
  db_path: "data/chatbot.db"
  vectordb_dir: "data/vectordb"

llm_config:
  chat_model: "mistral-large-latest"
  rag_model: "mistral-medium-latest"
  summary_model: "mistral-small-latest"
  temperature: 0.0

chat_history_config:
  max_history_pairs: 2
  max_characters: 1000
  max_tokens: 2000

agent_config:
  max_function_calls: 3

vectordb_config:
  collection_name: "chat_history"
  embedding_model: "mistral-embed"
  k: 3
